"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import { AlertCircle, ChevronLeft, ChevronRight, PackageSearch, Plus } from "lucide-react";
import { createProductAction, type ProductActionResult } from "../server/actions";
import { listProductsAction } from "../server/list-action";
import { PRODUCTS_PER_PAGE, type Product, type ProductStatusFilter } from "../types/product";
import { ProductCreateModal } from "./product-create-modal";
import { ProductsTable } from "./products-table";

type ProductsData = { products: Product[]; count: number; errorMessage: string | null };
export function ProductsManager({ query, status, page, isOwner, initialData }: { query: string; status: ProductStatusFilter; page: number; isOwner: boolean; initialData: ProductsData }) {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [notice, setNotice] = useState("");
  const productsQuery = useQuery({ queryKey: ["products", { q: query, status, page }], queryFn: () => listProductsAction(query, status, page), initialData });
  const createMutation = useMutation({ mutationFn: createProductAction, onSuccess: async (result) => { if (!result.success) return; await queryClient.invalidateQueries({ queryKey: ["products"] }); setOpen(false); setNotice(result.message); } });
  const data = productsQuery.data; const totalPages = Math.max(1, Math.ceil(data.count / PRODUCTS_PER_PAGE)); const from = data.products.length ? (page - 1) * PRODUCTS_PER_PAGE + 1 : 0; const to = from + data.products.length - 1;
  const href = (target: number) => `/productos?${new URLSearchParams({ ...(query ? { q: query } : {}), ...(status !== "todos" ? { estado: status } : {}), ...(target > 1 ? { page: String(target) } : {}) })}`;
  const create = async (formData: FormData): Promise<ProductActionResult> => createMutation.mutateAsync(formData);
  return <div className="space-y-4">{notice ? <p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{notice}</p> : null}{isOwner ? <div className="flex justify-end"><button type="button" onClick={() => setOpen(true)} className="inline-flex h-10 items-center gap-2 rounded-lg bg-neutral-900 px-4 text-sm font-medium text-white transition hover:bg-neutral-800"><Plus className="size-4" aria-hidden="true" />Nuevo producto</button></div> : null}{data.errorMessage ? <div role="alert" className="flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle className="mt-0.5 size-4 shrink-0" aria-hidden="true" />{data.errorMessage}</div> : data.products.length ? <><ProductsTable products={data.products} isOwner={isOwner} /><nav aria-label="Paginación" className="flex flex-wrap items-center justify-between gap-3 text-sm"><p className="text-neutral-500">Mostrando <span className="font-medium text-neutral-900">{from}–{to}</span> de <span className="font-medium text-neutral-900">{data.count}</span> · Página {page} de {totalPages}</p><div className="flex gap-2">{page > 1 ? <Link href={href(page - 1)} className="inline-flex h-9 items-center gap-1 rounded-lg border border-neutral-200 bg-white pl-2 pr-3 font-medium text-neutral-700"><ChevronLeft className="size-4" aria-hidden="true" />Anterior</Link> : null}{page < totalPages ? <Link href={href(page + 1)} className="inline-flex h-9 items-center gap-1 rounded-lg border border-neutral-200 bg-white pl-3 pr-2 font-medium text-neutral-700">Siguiente<ChevronRight className="size-4" aria-hidden="true" /></Link> : null}</div></nav></> : <div className="flex flex-col items-center rounded-xl border border-dashed border-neutral-300 bg-white px-6 py-14 text-center"><div className="flex size-11 items-center justify-center rounded-full bg-neutral-100 text-neutral-500"><PackageSearch className="size-5" aria-hidden="true" /></div><p className="mt-4 text-sm font-medium text-neutral-900">{query || status !== "todos" ? "Sin resultados" : "Aún no hay productos"}</p><p className="mt-1 max-w-xs text-sm text-neutral-500">{query || status !== "todos" ? "No encontramos productos con esos filtros." : "Registra tu primer producto para empezar a vender."}</p>{isOwner && !query && status === "todos" ? <button type="button" onClick={() => setOpen(true)} className="mt-5 inline-flex h-10 items-center gap-2 rounded-lg bg-neutral-900 px-4 text-sm font-medium text-white"><Plus className="size-4" aria-hidden="true" />Crear primer producto</button> : null}</div>}<ProductCreateModal open={open} isSaving={createMutation.isPending} onClose={() => setOpen(false)} onCreate={create} onCreated={() => undefined} /></div>;
}
